### ISSUE TITLE
highlight cells/slots upon hover

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2513]
Originally reported on Google Code with ID 2248

```
When I click on a slot, is displayed selectHelper with the time set in snapDuration.


It would be very useful to have available a listener to be able to display the selectHelper
with a certain time while moving the mouse over the calendar. 

For example, there are tasks with a specific time. The user could move the selectHelper
through the calendar looking for an empty space where the event can fit without overlapping.
```

Reported by `thiago@thiagomt.com` on 2014-08-19 22:09:48

Imported with **1** stars.

**Comment by julestruong** [comment]
Still nothing new on this ? i only want to change de background color when the mouse goes hover a day cell...

**Comment by akhramovichleverx** [comment]
Hello, any new feedback. Do you ETA for it?

**Comment by gregblass** [comment]
+1

**Comment by frlinw** [comment]
It's not possible to get a perfect result in pure css because of the dom architecture you can get something decent.

![image](https://user-images.githubusercontent.com/11896237/33848143-2c6354ec-dead-11e7-8404-32220dac36fe.png)

When my calendar become selectable, `.is-selectable` class is added on the fullcalendar container

```css
.is-selectable {
    .fc-agenda-view {
        .fc-body td {
            border-color: white;

            .fc-today {
                background-color: transparent;
            }
        }

        .fc-slats {
            z-index: 10;

            tr > td.fc-widget-content:last-child {
                background-color: var(--your-favorite-overlay-color);
                opacity: .3;
                cursor: pointer;

                &:hover {
                    opacity: .5;
                }
            }
        }

        .fc-bg {
            z-index: 11; // fc-bg z-index should be higher than fc-slats z-index to keep day borders visible
            pointer-events: none; // keep hover effect on fc-slats
        }
    }
}
```
