### ISSUE TITLE
horizontal scrolling in timeGrid views

### ISSUE THREAD

**Issue by babeuloula** [fullcalendar/fullcalendar#3022]
Hello, 
Is-it possible to scroll horizontally ?
Thanks

**Comment by dcryan** [comment]
@babeuloula, the [views](http://fullcalendar.io/docs/views/Available_Views/), not including the timeline views, do not scroll horizontally. What are you trying to achieve by scrolling horizontally?

**Comment by babeuloula** [comment]
Hello,

I use your plugin like this: 
![capture](https://cloud.githubusercontent.com/assets/4849233/12718487/2cf34dd4-c8ef-11e5-93bf-c4678a27fcdf.PNG)

And if I have to add a new column, it will be very small. And I would like to scroll horizontally to get a better view.

Thank you.

**Comment by arshaw** [comment]
Timeline view would probably be better suited for this. But I understand why someone might want this.

**Comment by r4j4h** [comment]
While not ideal, in the meantime perhaps one approach to getting what you desire is having your table wider than its container, and giving the container `overflow-x: scroll`?

For example, assuming you keep your calendar in some sort of container with the class `.calendar-container`:

```css
.calendar-container {
    width: 300px;
    overflow-x: scroll;
}

.calendar-container .fc-view > table {
    width: 500px;
}
```

For the table you want to make sure that you specify WHICH table element. For example, the headers are sometimes nested tables, and you *likely* don't want to affect them. Here, I tried to be specific and grab the closest table from the view, which in this case was a direct descendant from the view element. Please be sure to double check and alter as needed to suit your situation, but I checked the demos for both agenda week view and simple week view and both worked alright and were horizontally scrollable with those rules.

**Comment by babeuloula** [comment]
Thanks @r4j4h but with your code I don't see the times and the buttons.

Is it  possible to scroll only on this zone ?
![capture-d ecran-2016-02-03-11 46](https://cloud.githubusercontent.com/assets/4849233/12780071/12d357b8-ca6c-11e5-9def-10e63f87afad.png)

**Comment by r4j4h** [comment]
@babeuloula Sure!

```css
.calendar-container {
    width: 300px;
}

.calendar-container .fc-view {
    overflow-x: scroll;
}

.calendar-container .fc-view > table {
    width: 600px;
}
```

The container needs to have some sort of fixed width if you want to specify px/em in the inner table that will be scrollable.

If you use %s you could possibly get away with just

```css

.calendar-container .fc-view {
    overflow-x: scroll;
}

.calendar-container .fc-view > table {
    width: 200%;
}
```

At least it works in Chrome.

This allows me:
![1](https://cloud.githubusercontent.com/assets/703007/12806876/2853c202-cac7-11e5-8b3e-af1e976faed2.PNG)
![2](https://cloud.githubusercontent.com/assets/703007/12806877/2b39f93c-cac7-11e5-8b94-30a90be9fe27.PNG)

Is that more like what you are going for?
