### ISSUE TITLE
Control over slotLabel's HTML for more complex formatting

### ISSUE THREAD

**Issue by gansky-alexander** [fullcalendar/fullcalendar#3164]
Hello, all.

I need to style time in time axis with next:
hours in big font and minutes in small with underscore. Like next

![image2016-4-19 16 47 34](https://cloud.githubusercontent.com/assets/1111370/15254460/99ab2c4e-193f-11e6-9681-7e2409ec8f6b.png)

I think this two numbers should to be in different <span> and next i will make styles for it.

How can i make some kind of callback for rendering text in time axis?

**Comment by caseyjhol** [comment]
```js
$("#calendar").fullCalendar({
    slotLabelFormat: 'h'
});
```

```css
.fc-time span:after {
  content: '00';
  font-size: 0.5em;
  vertical-align: top;
}
```
