### ISSUE TITLE
Event wrap text, and sticky headers in print view

### ISSUE THREAD

**Issue by missweizhang** [fullcalendar/fullcalendar#3502]
Hi, 

I would like to request that events with long names be allowed to wrap text in month view, as such

![image](https://cloud.githubusercontent.com/assets/19189069/22238022/e7dd2294-e1c3-11e6-9879-151d9b4862e9.png)

I got the above by adding to the `<style>` element in [demos/gcal.html](https://github.com/fullcalendar/fullcalendar/files/725930/gcal.html.txt)
``` css
	table div div {
		overflow: inherit !important;
		white-space: normal !important;
	}
```
But i need help fixing:
1. the extra scrollbars on the right need to be gone.
2. when printing, the headers need to be repeated on the next page, and the date numbers moved with the content to the next page:
![image](https://cloud.githubusercontent.com/assets/19189069/22238110/6f16faa0-e1c4-11e6-9543-4fb95f7bed5b.png)

Thanks a lot for your help!  Good work, guys!
Wei
