### ISSUE TITLE
Enhancement: Now indicator spread across entire week view option.

### ISSUE THREAD

**Issue by CollinHerber** [fullcalendar/fullcalendar#4609]
Now indicator spread across entire week view option.

Codepen:
https://codepen.io/anon/pen/BEKjYr

Picture of expected:
http://prntscr.com/n7j3ls

I've been playing around seeing if I can custom style it to do such, but with no such luck. 
If anyone has a work-around lmk, otherwise would love to see this implemented.

**Comment by frlinw** [comment]
![image](https://user-images.githubusercontent.com/11896237/55618900-eed31580-5797-11e9-9070-ac312df6d5be.png)

**Comment by CollinHerber** [comment]
@frlinw Other than the issues with the arrow itself not showing correctly, that was able to make it span across the entire page. Would still be nice to see something native.

**Comment by frlinw** [comment]
It was just to show you that you can do whatever you want. You can let the arrow and use the `::before` or `::after` pseudo element to print the line if you prefer.
Styles are opinionated, if you need something different, you can easily override.

**Comment by patrickbattisti** [comment]
hi,

my code
```

.fc-now-indicator.fc-now-indicator-arrow::before {
  background-color: #ef6c00;
  content: "";
  display: block;
  width: 15px;
  height: 15px;
  border-radius: 50%;
  margin-top: -7px;
}

.fc-now-indicator.fc-now-indicator-arrow {
  left: 44px !important;
  right: 0;
  background-color: #ef6c00;
  height: 2px;
  margin: 0;
  border: none;
}
```

![Screen Shot 2019-06-25 at 05 55 10](https://user-images.githubusercontent.com/35247414/60084501-0aeab100-970e-11e9-9494-329d3766cfd1.png)

**Comment by arshaw** [comment]
FC's API should probably have an official setting to control this. Nice workaround in the meantim

**Comment by tanmay-joshi-tfs** [comment]
Is this workaround valid in v5 as well? fc-timegrid-now-indicator-container is attached to timegrid columns, which is making it difficult to make the now-indicator line span across the week

**Comment by mengdi** [comment]
Same problem here. It is difficult to span now-indicator across the week since the div .fc-timegrid-now-indicator-arrow is missing in other week days.

**Comment by frlinw** [comment]
Try something like this (and be careful of css specificity):
```
  .fc-media-screen .fc-timegrid-now-indicator-container {
    position: unset;
  }

  .fc .fc-timegrid-now-indicator-line {
    border-bottom-width: 1px; 
    border-top-width: 1px;
    border-color: red;
    background-color: red;
  }

  // Day view
  .fc-resourceTimeGridDay-view  .fc-timegrid-now-indicator-arrow {
    position: absolute;
    border: none;
    left: unset;
    right: -6px;
    width: 12px;
    height: 12px;
    background-color: red;
    border-radius: 50%;
  }
   
  // Week view
  .fc-timeGridWeek-view .fc-timegrid-now-indicator-arrow {
    display: none;
  }

  .fc-timeGridWeek-view .fc-timegrid-now-indicator-line::before {
    content: "";
    position: absolute;
    top: -6px;
    left: -6px;
    width: 12px;
    height: 12px;
    background-color: red;
    border-radius :50%;
  }
```

**Comment by tylerturdenpants** [comment]
@patrickbattisti can you show me how you got the round indicator to be like it is (in the middle of the of the event space and the time) in https://github.com/fullcalendar/fullcalendar/issues/4609#issuecomment-505353735

**Comment by zpalcnik** [comment]
I had the same problem.., here is one simple solution (workaround...)

`  .fc-timegrid-now-indicator-container {
    overflow: visible !important;
    .fc-timegrid-now-indicator-line {
      width: calc(500% + 4px) !important;
    }
  }
  .fc-day-tue {
    .fc-timegrid-now-indicator-line {
      transform: translateX(-20%);
    }
  }
  .fc-day-wed {
    .fc-timegrid-now-indicator-line {
      transform: translateX(-40%);
    }
  }
  .fc-day-thu {
    .fc-timegrid-now-indicator-line {
      transform: translateX(-60%);
    }
  }
  .fc-day-fri {
    .fc-timegrid-now-indicator-line {
      transform: translateX(-80%);
    }
  }`

**Comment by Troy-Yang** [comment]
any solution on v5? it's hard to span it across week.

**Comment by Troy-Yang** [comment]
Just figure out a solution in V5 with nowIndicatorDidMount by appending a past line after the now indicator. The key is adding a width with **past  weekday** * indicator width, the same as the left position.

The below solution supports firstdayofweek and no-weekend. 

CSS
`
    .fc-timegrid-now-indicator-container {
      overflow: visible;
     .fc-timegrid-now-indicator-line--passed {
        position: absolute;
        height: 1px;
        border-width: 1px 0 0;
        border-color: color.$primary-100;
        border-style: dotted;
        transform: translate(2px, -1px);
      }
    }
`

nowIndicatorDidMount = ({ el, date }) => applyPassedIndicator

TS 
`
const createPassedLineIndicatorElement = (passedDays: number, actualDayWidth: number) => {
  const previousIndicator = document.createElement('span');
  previousIndicator.classList.add('fc-timegrid-now-indicator-line--passed');
  previousIndicator.style.width = `${passedDays * actualDayWidth}px`;
  previousIndicator.style.left = `${-passedDays * actualDayWidth}px`;
  return previousIndicator;
};

const applyPassedIndicator = (
  root: HTMLElement, today: Date,
  { firstDayOfWeek, includeWeekends }: { firstDayOfWeek: number, includeWeekends: boolean },
) => {
  if (!root.classList.contains('fc-timegrid-now-indicator-line')) return;

  const passedDays = findPassedWeekDays(today, firstDayOfWeek, includeWeekends);
  if (passedDays) {
    const actualDayWidth = root.clientWidth > dayMinWidth ? root.clientWidth : dayMinWidth - 1;
    const previousIndicator = createPassedLineIndicatorElement(passedDays, actualDayWidth);
    root.appendChild(previousIndicator);
  }
};

`

get passed day:
`
import range from 'lodash/range';

const WEEK_DAYS = range(7);
const WEEKEND_DAYS = [ 0, 6 ];

export const shiftWeekArray = (length: number) => {
  let i = length;
  const weekDays = [ ...WEEK_DAYS ];
  while (i > 0) {
    const first = weekDays.shift() as number;
    weekDays.push(first);
    i--;
  }
  return weekDays;
};

export const findPreviousLength = (arr: number[], current: number, ignoreItems: number[] = []) => {
  let passedDays = 0;
  let i = 0;
  while (i < arr.length) {
    if (current === arr[i]) break;
    if (!ignoreItems.includes(arr[i])) passedDays++;
    i++;
  }
  return passedDays;
};

export const findPassedWeekDays = (today: Date, firstDayOfWeek: number, includeWeekends: boolean) => {
  const passedDays = findPreviousLength(
    shiftWeekArray(firstDayOfWeek),
    today.getDay(),
    includeWeekends ? [] : WEEKEND_DAYS,
  );
  return passedDays;
};
`

**Comment by Troy-Yang** [comment]
![image](https://user-images.githubusercontent.com/3301669/180593488-b2b26f09-45a2-470b-8565-4cb2c2a918bf.png)

**Comment by gnapse** [comment]
I managed to make it work using fullcalendar v6, following @zpalcnik's [comment above](#issuecomment-1010706978). Here's the code as I adapted it to fit my needs (7-day weekview):

```css
/**
 * Fully expanded "now" indicator line
 * @see https://github.com/fullcalendar/fullcalendar/issues/4609#issuecomment-1010706978
 */

.fc-timeGridWeek-view .fc-timegrid-now-indicator-container {
    overflow: visible !important;
}
.fc-timeGridWeek-view .fc-timegrid-now-indicator-line {
    width: calc(700% + 6px) !important;
}

/**
 * The use of nth-child is to address the day columns depending on their order.
 *
 * - The 1st column does not correspond to any day, but it's the column that shows the timegrid
 *   timeline.
 * - The 2nd column corresponds to the 1st day of the week view. This is the one with 0% below.
 * - We continue with each subsequent column, incrementing its percentage in 1/7 each time.
 *
 * By addressing day columns by their order, instead of by their weekday class name
 * (e.g. .fc-day-fri) we guarantee that this solution works regardless of what the first day of the
 * week is.
 */
.fc-timeGridWeek-view .fc-day:nth-child(2) .fc-timegrid-now-indicator-line {
    --fc-now-indicator-shift: 0%;
}
.fc-timeGridWeek-view .fc-day:nth-child(3) .fc-timegrid-now-indicator-line {
    --fc-now-indicator-shift: 14.29%;
}
.fc-timeGridWeek-view .fc-day:nth-child(4) .fc-timegrid-now-indicator-line {
    --fc-now-indicator-shift: 28.57%;
}
.fc-timeGridWeek-view .fc-day:nth-child(5) .fc-timegrid-now-indicator-line {
    --fc-now-indicator-shift: 42.86%;
}
.fc-timeGridWeek-view .fc-day:nth-child(6) .fc-timegrid-now-indicator-line {
    --fc-now-indicator-shift: 57.14%;
}
.fc-timeGridWeek-view .fc-day:nth-child(7) .fc-timegrid-now-indicator-line {
    --fc-now-indicator-shift: 71.43%;
}
.fc-timeGridWeek-view .fc-day:nth-child(8) .fc-timegrid-now-indicator-line {
    --fc-now-indicator-shift: 85.71%;
}

.fc-timeGridWeek-view .fc-day .fc-timegrid-now-indicator-line {
    transform: translateX(calc(-1 * var(--fc-now-indicator-shift)));
}
```

## Bonus: dot-marker aligned with the "today" column:

```css
.fc-timeGridWeek-view .fc-timegrid-now-indicator-line::before {
    position: absolute;
    display: block;
    content: '';
    margin-top: -4px;
    width: 8px;
    height: 8px;
    border-radius: 8px;
    background-color: var(--fc-now-indicator-color);
    left: calc(var(--fc-now-indicator-shift) - 4px);
}
```

This mimics the Apple Calendar app:

![CleanShot 2023-03-31 at 15 34 45@2x](https://user-images.githubusercontent.com/15199/229202431-894bf558-8159-42b7-80d2-a026556805b6.png)
