### ISSUE TITLE
Header row - stack on mobile view

### ISSUE THREAD

**Issue by neilakapete** [fullcalendar/fullcalendar#4638]
Using chrome dev tools you can see how the header row is squashed

![image](https://user-images.githubusercontent.com/9258317/56428145-f8727800-6283-11e9-9a30-2616a9160818.png)

It would be nice if it were stacked similar to this 
![image](https://user-images.githubusercontent.com/9258317/56430404-e1d01f00-628b-11e9-90d8-14e82f993575.png)

**Comment by ex1st** [comment]
You can move several buttons to footer, for example

![footer](https://user-images.githubusercontent.com/7733915/56445171-84c47f80-6304-11e9-9385-526dc7a32344.png)

**Comment by acerix** [comment]
Thanks for the report, I can see this on the homepage demo by making the browser window smaller. The way they get stacked without any space does not look great.

https://fullcalendar.io/

**Comment by JulidaRocks** [comment]
Any progress to this issue?

**Comment by borisbsu** [comment]
This can be easily done with CSS Flexbox. Here is example:

```css
@media(max-width: 767px) {
  .fc-toolbar.fc-header-toolbar {
    display: flex;
    flex-direction: column;
  }
  .fc-toolbar.fc-header-toolbar .fc-left {
    order: 3;
  }
  .fc-toolbar.fc-header-toolbar .fc-center {
    order: 1;
  }
  .fc-toolbar.fc-header-toolbar .fc-right {
    order: 2;
  }
}
```

![image](https://user-images.githubusercontent.com/556093/74085491-73fb1b00-4a8a-11ea-8d05-9dfb037c7bf6.png)
