### ISSUE TITLE
Ability to use Tailwind CSS as another theme system

### ISSUE THREAD

**Issue by mintotsai** [fullcalendar/fullcalendar#5868]
### Checklist

Please mark these items with an [x]

  - [x ] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

FullCalendar's current themeSystem supports Bootstrap. Would love to see Tailwind as another option.

**Comment by Edgarborras94** [comment]
Sure! but there is a thing to taking note; Bootstrap do have several css classes presets (aka components) but tailwind does not have those things, i.e:

- a button in bootstrap could simply be: ```<button class="btn btn-primary">...```

- a button in tailwind css would be: ```<button class="bg-indigo-600 text-white focus:bg-indigo-700 hover:bg-indigo-500...```

Of course it would be a nice addition but it shoud be a super addition in terms of customization, letting people choose classes for each component styled.

Please don't missunderstand my comment, I only try to put things in perspective if people come here from Google or something

Cheers!

**Comment by pA1nD** [comment]
You can use tailwind with the @apply feature.
e.g.

```
.fc-view-harness {
  @apply overflow-hidden overflow-x-auto shadow;
}

@screen sm {
  .fc-view-harness {
    @apply rounded-lg;
  }
}
```

If the classes would be better documented and there would be a way to disable the auto loading of css, it would be easily possible to create themes this way.

Could be included as @import in the tailwind.css

**Comment by pA1nD** [comment]
I'm struggling to understand the `themeSystem` parameter. It seems to not be possible to just set a random string to configure my own theme and not load the default styles? Is there a way to not include default styles?

**Comment by stehag** [comment]
Support for tailwind would be awesome!.  +1

**Comment by gbrits** [comment]
Tailwind released an official UI set for calendars today.  📅

[You can check it out here.](https://tailwindui.com/components/application-ui/data-display/calendars)

Hopefully someone has the time & energy to pour into porting this for FullCalendar so the world can benefit from a clean 2022 calendar view-set that works with FullCalendar out of the box. 🤞

**Comment by eskiesirius** [comment]
Any update on this?

**Comment by NovaFox161** [comment]
I don't mean to necro, but it would be fantastic if this could get added. Struggling to cleanly override the default styles (notably the toolbar button styles)

**Comment by AiFxApp** [comment]
I have FullCalender working on my Tailwind project? populates after event created etc?

**Comment by gbrits** [comment]
@NovaFox161 here are some styles that could help you get started:
```
.fc .fc-toolbar-title {
    font-size: 1.25rem !important;
    margin: 0;
    font-weight: 500;
    padding: 20px 0 0px 20px;
}

.fc .fc-button {
    background-color: #006082 !important;
    border-color: #006082 !important;
}

.fc-day-today {
    background-color: #edf5f7 !important;
}

.fc-theme-standard td {
    border: 1px solid #e5e7eb !important;
} 

.fc-day-other {
    background: #FAFAFB;
}

.fc .fc-button .fc-icon {
    font-size: 0.875rem !important;
}

a.fc-col-header-cell-cushion {
    font-size: .85em !important;
    line-height: 2.2rem !important;
    font-weight: 600 !important;
}

.fc .fc-daygrid-day-top {
    flex-direction: inherit !important;
    padding: 5px !important;
    font-size: .75em !important;
    color: #6b7280 !important;
}

.fc .fc-button-primary:disabled {
    background-color: #eeeeee !important;
    color: black !important;
    border-color: #eeeeee !important;
    font-size: 0.875rem !important;
    line-height: 1.25rem !important;
    text-transform: capitalize !important;
}
```

**Comment by ckluis** [comment]
Tailwind has picked up a lot of steam relative to bootstrap.  Is official tailwind support being considered?

**Comment by gmwill934** [comment]
Would be really cool!

**Comment by Edgarborras94** [comment]
> Sure! but there is a thing to taking note; Bootstrap do have several css classes presets (aka components) but tailwind does not have those things, i.e:
> 
> * a button in bootstrap could simply be: `<button class="btn btn-primary">...`
> * a button in tailwind css would be: `<button class="bg-indigo-600 text-white focus:bg-indigo-700 hover:bg-indigo-500...`
> 
> Of course it would be a nice addition but it shoud be a super addition in terms of customization, letting people choose classes for each component styled.
> 
> Please don't missunderstand my comment, I only try to put things in perspective if people come here from Google or something
> 
> Cheers!

After 2 years of this comment, I now need a fullcalendar with tailwindcss, so might try to add a tailwind option for fullcalendar and if I'm successful will make a PR. Might be in the next 2 weeks/months (the dates I need the calendar)

**Comment by james-phillips-haysto** [comment]
This would be a match made in calendar heaven

**Comment by suspence21** [comment]
> Sure! but there is a thing to taking note; Bootstrap do have several css classes presets (aka components) but tailwind does not have those things, i.e:
> 
> * a button in bootstrap could simply be: `<button class="btn btn-primary">...`
> * a button in tailwind css would be: `<button class="bg-indigo-600 text-white focus:bg-indigo-700 hover:bg-indigo-500...`

You need to look into using DaisyUI that currently makes use of all the TailwindCSS classes to utilize features that Bootstrap has, like `btn btn-primary` etc. Please consider.

**Comment by vinnygambiny** [comment]
> > Sure! but there is a thing to taking note; Bootstrap do have several css classes presets (aka components) but tailwind does not have those things, i.e:
> > 
> > * a button in bootstrap could simply be: `<button class="btn btn-primary">...`
> > * a button in tailwind css would be: `<button class="bg-indigo-600 text-white focus:bg-indigo-700 hover:bg-indigo-500...`
> > 
> > Of course it would be a nice addition but it shoud be a super addition in terms of customization, letting people choose classes for each component styled.
> > Please don't missunderstand my comment, I only try to put things in perspective if people come here from Google or something
> > Cheers!
> 
> After 2 years of this comment, I now need a fullcalendar with tailwindcss, so might try to add a tailwind option for fullcalendar and if I'm successful will make a PR. Might be in the next 2 weeks/months (the dates I need the calendar)

@Edgarborras94 Any news with this ? 😄

**Comment by jackpaulcollins** [comment]
+1 on this

**Comment by bernlorbis** [comment]
+1

**Comment by erbilozum** [comment]
+1

**Comment by ClemRiviere** [comment]
+1

**Comment by Marthianfred** [comment]
+1

**Comment by timbogdanov** [comment]
Is there any update on this?

**Comment by wmtrinu** [comment]
will this be a reality? :)

**Comment by andrevferreiraa** [comment]
Also hoping for this!

**Comment by blcksheep80** [comment]
+1 For Tailwind support :)

**Comment by cain** [comment]
+1 for tailwind!

**Comment by yonaries** [comment]
Anything new on Tailwind support or a work around way?

**Comment by ClemRiviere** [comment]
> Anything new on Tailwind support or a work around way?

As far as I know, still not Tailwind support. Here is a workaround using `@apply` in css : 

```scss
/* Event calendar */
.fc-event {
    @apply bg-primary-400 border-primary-400 #{!important};
}

/* Non business hours */
.fc-non-business {
    @apply bg-gray-400 bg-opacity-30 #{!important};
}
```

You can user this exemple with every fullcalendar CSS classes I think.

**Comment by Visnicio** [comment]
@ClemRiviere just to clarify, your example is working with sass, isn't it?

**Comment by ClemRiviere** [comment]
> @ClemRiviere just to clarify, your example is working with sass, isn't it?

@Visnicio yes it is working with sass, but this is only a small part of what would need to be done to have a complete interface in tailwind.

**Comment by Darlley** [comment]
# ReactJS and TailwindCSS


![image](https://github.com/fullcalendar/fullcalendar/assets/37590954/cfec6583-789b-4cb1-af98-0b4d2681338d)

```js
<FullCalendar
          dayCellClassNames={"hover:bg-gray-600/50"}
          plugins={[dayGridPlugin, interactionPlugin, listPlugin]}
          initialView="dayGridMonth"
          headerToolbar={{
            left: "prev,next,today",
            center: "title",
            right: "dayGridMonth,dayGridWeek,dayGridDay,listMonth",
          }}
          locale={ptBrLocale}
          dayMaxEventRows={1}
          eventClassNames={
            "bg-transparent hover:bg-slate-800/60 p-1 text-xs border-none"
          }
          events={allEvents}
          nowIndicator={true}
          editable={true}
          droppable={true}
          drop={(data) => addEvent(data)}
          dateClick={() => setOpenModalEmptyTask(true)}
          eventClick={(data) => setOpenModalEditTask(true)}
          navLinkDayClick="dayGridDay"
          navLinks={true}
/>
```

Styles with classes `apply`:

```css
/*
  FULLCALENDAR 
*/

.fc-button {
  @apply py-1 px-2.5 bg-growp-500 hover:bg-gray-950 m-0 h-[36px] border-none focus:ring-1 focus:ring-growp-900 focus:outline-1 focus:outline-growp-900 !important
}

.fc-button-group {
  @apply space-x-0 !important
}

.fc-toolbar-chunk {
  @apply space-x-4 !important
}

.fc-today-button:disabled {
  @apply bg-gray-800/50 !important
}

.fc-today-button.fc-button-primary:not(.fc-today-button:disabled) {
  @apply bg-growp-900 hover:bg-gray-950 transition-colors !important
}

.fc-theme-standard td,
.fc-theme-standard th,
.fc-theme-standard .fc-scrollgrid {
  @apply border-gray-600/10 !important
}

.fc-button.fc-button-primary.fc-button-active {
  @apply bg-gray-800 !important
}

.fc-toolbar-title {
  @apply text-center text-xl font-semibold !important
}

.fc-day.fc-day-fri.fc-day-today.fc-daygrid-day {
  @apply bg-sky-900/60 !important
}

.fc.fc-media-screen.fc-direction-ltr.fc-theme-standard {
  @apply w-full md:min-w-[450px] !important
}

.fc-highlight {
  @apply bg-sky-400/10 !important
}

.fc-header-toolbar.fc-toolbar.fc-toolbar-ltr {
  @apply flex md:flex-row flex-col-reverse md:items-center items-start md:justify-between justify-start gap-2 !important
}

.fc-popover {
  @apply z-[1] !important
}

/* Fullcalendar visualização em lista */
.fc .fc-list-sticky .fc-list-day > th {
  @apply bg-growp-500 text-white !important
}
.fc-theme-standard .fc-list-day-cushion{
  @apply bg-none !important
}
.fc-listMonth-view,
.fc-dayGridWeek-view.fc-view.fc-daygrid {
  @apply bg-transparent text-gray-500 !important
}

.fc-list-event:hover {
  @apply text-growp-500 cursor-pointer !important
}

.fc-dayGridDay-view.fc-view.fc-daygrid .fc-daygrid-day-frame.fc-scrollgrid-sync-inner {
  @apply bg-gray-900 !important
}

.fc-popover-header {
  @apply bg-gray-900 text-gray-400 !important
}

.fc-popover-body {
  @apply bg-gray-900 !important
}
```

**Comment by justin-hackin** [comment]
> ```js
> eventClassNames={
>             "bg-transparent hover:bg-slate-800/60 p-1 text-xs border-none"
>           }
> ```

Can you publish an example project of this? I tried to duplicate it but I get this error message when I import the css.

```
The `bg-growp-500` class does not exist. If `bg-growp-500` is a custom class, make sure it is defined within a `@layer` directive.
```

**Comment by ClemRiviere** [comment]
@justin-hackin this class seems to be a tailwind custom color based class : https://tailwindcss.com/docs/customizing-colors#using-custom-colors. If you need to use your custom color (or an existing tailwind one), you should be able to change `bg-growp-500` for `bg-red-500` for exemple (red-500 background)

**Comment by tiagobnobrega** [comment]
For anyone using shadcn this could be a starting point:

```css
/*full-calendar-shadcn.css*/
.fc.fc-theme-standard {
    --fc-small-font-size: .85em;
    --fc-page-bg-color: hsla(var(--background));
    --fc-neutral-bg-color: hsla(var(--muted)/ 0.7);
    --fc-neutral-text-color: hsla(var(--muted-foreground));
    --fc-border-color: hsla(var(--border));
    --fc-button-text-color: hsla(var(--primary-foreground));
    --fc-button-bg-color: hsla(var(--primary));
    --fc-button-border-color: hsla(var(--border));
    --fc-button-hover-bg-color: hsla(var(--primary) / 0.9);
    --fc-button-hover-border-color: hsla(var(--border));
    --fc-button-active-bg-color: hsla(var(--primary) / 0.8);
    --fc-button-active-border-color: hsla(var(--border));
    --fc-event-bg-color: hsla(var(--primary-foreground));
    --fc-event-border-color: hsla(var(--border));
    --fc-event-text-color: hsla(var(--primary));
    --fc-event-selected-overlay-color: hsla(var(--primary) / 0.4);
    --fc-more-link-bg-color: #d0d0d0;
    --fc-more-link-text-color: hsla(var(--primary));
    --fc-event-resizer-thickness: 8px;
    --fc-event-resizer-dot-total-width: 8px;
    --fc-event-resizer-dot-border-width: 1px;
    --fc-non-business-color: hsla(var(--muted) / 0.2);
    --fc-bg-event-color: #8fdf82;
    --fc-bg-event-opacity: 0.3;
    --fc-highlight-color: hsla(var(--ring));
    --fc-today-bg-color: hsla(var(--accent));
    --fc-now-indicator-color: red;
}
```
