### ISSUE TITLE
All timeGrid events have the inset harness class

### ISSUE THREAD

**Issue by baileyandy** [fullcalendar/fullcalendar#6512]
### Reduced Test Case

https://fullcalendar.io/docs/timeZone-demo (or any of the demos using `v5.7.0+`)

### Bug Description

As of `v5.7.0` all timeGrid events are given the class `.fc-timegrid-event-harness-inset` and not just the events that _are_ inset. It still seems to be the case in `v5.9.0` which is the version the demo link above uses and screenshot below is taken from. It's not particularly noticeable with a white background but I've edited the background to black for the screenshot to highlight the inset border around every event.

I believe the`.fc-timegrid-event-harness-inset` class should only be for _inset_ items.

### Screenshots

<img width="831" alt="Screenshot 2021-08-13 at 11 00 23" src="https://user-images.githubusercontent.com/482092/129340454-4187c03a-4027-4f9c-84d4-81f309156591.png">

**Comment by minhhdl** [comment]
I am facing the same issue after upgrading to v5.9.0 :(

**Comment by baileyandy** [comment]
I have figured out some workarounds for now...

If you want to remove the border for _all events_, use

```css
.fc-timegrid-event-harness-inset .fc-timegrid-event {
  box-shadow: none;
}
```

If you want to target _just the inset items_ again, we need to use some code and CSS. The code adds a new class to the "real inset" events and the CSS can then style just those events

```tsx
eventDidMount={(arg: MountArg<EventContentArg>): CustomContentGenerator<EventContentArg> => {
    const eventParent = arg.el.parentElement

    if (eventParent.style.inset.endsWith('50%')) {
        arg.el.parentElement.classList.add('real-inset')
    }

    return undefined
}}
```

and for example I didn't want the event titles on the short events to wrap, so I use

```css
.real-inset .fc-timegrid-event.fc-timegrid-event-short .fc-event-title {
  white-space: nowrap;
}
```
