### ISSUE TITLE
fc-list-day  is not overlaping the table on list-view - only Firefox

### ISSUE THREAD

**Issue by FeehGb** [fullcalendar/fullcalendar#6896]
### Reduced Test Case
"not reproducible with a link"

### Bug Description
The bug is when the day list is too large and create right scroll bar;
It's should be sticky and overlap the table

### How I Fixed
I fixed on css:
```css
.fc .fc-list-sticky .fc-list-day > * { 
    z-index: 1;
    position: -webkit-sticky;
    position: sticky;
    top: 0;
    background: var(--fc-page-bg-color,#fff);
}
```
### Screenshots
![image](https://user-images.githubusercontent.com/43045359/175056738-ce04923d-00e3-4ab9-9eaf-b1a14fdb4f75.png)

![image](https://user-images.githubusercontent.com/43045359/175057011-e4705fa2-721f-4bcc-a2da-682a382784ae.png)
