### ISSUE TITLE
Improve Bootstrap 5 theme color mode

### ISSUE THREAD

**Issue by lianee** [fullcalendar/fullcalendar#7465]
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

Bootstrap 5 now has a color modes, starting whith dark mode
The bootstrap 5 theme should respect the bootstrap colors, which change depending of the selected mode, for example var(--bs-border-color) instead of var(--bs-gray-400) for borders

**Comment by lianee** [comment]
Here is a simple scss code that improve appearance between light and dark modes:
```scss
.fc-theme-bootstrap5 {
  .fc-list,
  .fc-scrollgrid,
  td,
  th {
    border: 1px solid var(--bs-border-color);
  }
  .fc-scrollgrid-section-sticky > * {
    background-color: var(--bs-table-bg);
  }
  .fc-cell-shaded,
  .fc-day-disabled {
    background: rgba(var(--bs-emphasis-color-rgb), 0.05);
  }
  .fc-daygrid-day.fc-day-today {
    background-color: var(--bs-info-bg-subtle);
  }
}
```
