### ISSUE TITLE
FullCalendar React css style and/or icons not working in PROD

### ISSUE THREAD

**Issue by pellea** [fullcalendar/fullcalendar#7702]
### Reduced Test Case

na

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

Hello,

There are issue with styling in production build (React + Vite).

For example, the icons of buttons are not displayed in PROD but correctly displayed in DEV. The style of the button doesn't look like the online demo either (with default theme, not bootstrap).

It seems that for the v6 we don't need to import CSS anymore or do some workarounds but all the example are using either webpack or rollup. With `Vite`, it's not working.

How do we need to import the CSS correctly ?

in DEV:
![image](https://github.com/fullcalendar/fullcalendar/assets/395982/e4583df5-7432-474e-ba6f-d1de5e5565a2)

in PROD:
![image](https://github.com/fullcalendar/fullcalendar/assets/395982/db77bece-6c35-405d-bf63-2628f4a28e1b)

Usage:
```tsx
import { EventApi, DateSelectArg, EventContentArg, EventInput } from '@fullcalendar/core';
import frLocale from '@fullcalendar/core/locales/fr';
import FullCalendar from '@fullcalendar/react';
import dayGridPlugin from '@fullcalendar/daygrid';
import timeGridPlugin from '@fullcalendar/timegrid';
import interactionPlugin from '@fullcalendar/interaction';
import multiMonthPlugin from '@fullcalendar/multimonth';
import listPlugin from '@fullcalendar/list';

...

<FullCalendar
    locale={frLocale}
    themeSystem="standard"
    height={height}
    plugins={[dayGridPlugin, timeGridPlugin, interactionPlugin, multiMonthPlugin, listPlugin]}
    headerToolbar={{
      left: 'prev,next today',
      center: 'title',
      right: 'dayGridMonth,timeGridWeek,timeGridDay,multiMonthYear,listWeek'
    }}
    dayHeaders={true}
    firstDay={1}
    nowIndicator={true}
    navLinks={true}
    initialView="dayGridMonth"
    editable={false}
    selectable={false}
    selectMirror={false}
    dayMaxEvents={true}
    weekends={false}
    weekNumbers={true}
    events={events}
    select={handleDateSelect}
    eventContent={renderEventContent} // custom render function
    eventsSet={handleEvents}
  />
```

**Comment by pellea** [comment]
Using FontAwsome icons as a workaround fixed the issue ... but why in "PROD/Realease" build icons are not displayed?

```css
  .fc-icon-chevron-left:before {
    font-family: 'Font Awesome 5 Free';
    content: '\uf053';
    font-size: 16px;
    font-weight: 900;
    box-sizing: border-box;
    display: inline-block;
    vertical-align: middle;
    text-align: center;
    text-rendering: auto;
    -webkit-font-smoothing: antialiased;
    position: absolute;
    left: 50%;
    top: 50%;
    transform: translate(-50%, -50%);
  }

  .fc-icon-chevron-right:before {
    font-family: 'Font Awesome 5 Free';
    content: '\uf054';
    font-size: 16px;
    font-weight: 900;
    box-sizing: border-box;
    display: inline-block;
    vertical-align: middle;
    text-align: center;
    text-rendering: auto;
    -webkit-font-smoothing: antialiased;
    position: absolute;
    left: 50%;
    top: 50%;
    transform: translate(-50%, -50%);
  }
```
