### ISSUE TITLE
Unable to target scrollbar for custom styles

### ISSUE THREAD

**Issue by karuppusamy-d** [fullcalendar/fullcalendar#7909]
### Reduced Test Case

https://codepen.io/KaruppusamyD/pen/PwoQdON

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [x] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

While attempting to customize scrollbar styles using the .fc-scroller class, FullCalendar is not applying the intended width or height changes to the scrollbars. 

This issue appears to override or ignore the custom styles linked with .fc-scroller and affects the visual consistency.

```css
.fc-scroller {
  padding-right: 0;
}

.fc-scroller::-webkit-scrollbar {
  width: 6px;
  height: 6px;
}

.fc-scroller::-webkit-scrollbar-track {
  margin: 0.25rem 0.5rem;
  background-color: transparent;
}

.fc-scroller::-webkit-scrollbar-thumb {
  border-radius: 0.25rem;
  background-color: hsl(214 32% 80%/0.6);
}

.fc-scroller::-webkit-scrollbar-thumb:hover {
  background-color: hsl(214 32% 80%/0.8);
}

.fc-scroller::-webkit-scrollbar-thumb:active {
  background-color: hsl(214 32% 80%);
}
```

![Image](https://github.com/user-attachments/assets/7ac22817-6805-4bfc-a018-7cc84dd34cde)
